#用于配置服务器tomcat的端口
server:
  port: 8081
#"JDBC:SQLSERVER://localhost:1433:databaseName=demo"
spring:
  #多个数据库源的引用配置
  datasource:
    primarily:
      url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
    secondly:
      url: jdbc:mysql://127.0.0.1:3306/testdb2?useUnicode=true&characterEncoding=utf-8
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/demo2?useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      database: mysql
      show-sql: true
#数据库分布式管理的 配置 主要使用atomikos 插件来实现
  jta:
    atomikos:
      datasource:
        max-pool-size: 20
        borrow-connection-timeout: 60
      connectionfactory:
        borrow-connection-timeout: 60
        max-pool-size: 20

  #用于时间转换由string 转成date对象
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+12
# 1.一个家庭由爸爸 妈妈 孩子
#2. 这个家庭有一个名字（family-name）叫做 happy family
#3. 爸爸有名字name 和年龄 age
#4. 妈妈有两个别名
#5. 孩子除了名字name和年龄age 还有一个friends集合
#6. 每个friend有两个属性 hobby爱好和性别sex
family:
  family-name: "happy family"
  father:
    name:
    #年龄取随机数
    age: ${random.int(10,100)}
  mother:
    allias:
      - yuanyuan
      - rain
  child:
    #条件取值，如果没有family father mother，则取默认值haoen
    name: ${family.father.mother:haoen}
    age: 18
    friends:
      - hobby: football
        sex: male
      - hobby: basketball
        sex: female

